CREATE TABLE `user` (
	`id`	INT	NOT NULL	AUTO_INCREMENT,
	`auth_id`	VARCHAR(50)	NOT NULL,
	`user_name`	VARCHAR(45)	NOT NULL,
	`is_active`	BOOLEAN	NOT NULL	DEFAULT TRUE,
	`email`	VARCHAR(100)	NOT NULL,
	`created_at`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`updated_at`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`is_valid`	BOOLEAN	NOT NULL	DEFAULT TRUE,
    PRIMARY KEY (`id`),
    UNIQUE KEY `auth_id` (`auth_id`),
    UNIQUE KEY `email` (`email`)
);

CREATE TABLE `requested_book` (
	`id`	INT	NOT NULL    AUTO_INCREMENT,
	`user_id`	INT	NOT NULL,
	`book_title`	VARCHAR(255)	NOT NULL,
	`publication_year`	YEAR	NULL,
	`reject_reason`	TEXT	NULL,
	`request_link`	VARCHAR(100)	NOT NULL,
	`reason`	TEXT	NOT NULL,
	`processing_status`	TINYINT	NOT NULL	DEFAULT 0,
	`request_date`	DATE	NOT NULL,
	`created_at`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`updated_at`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`is_valid`	BOOLEAN	NOT NULL	DEFAULT FALSE,
    PRIMARY KEY (`id`),
    FOREIGN KEY (`user_id`) REFERENCES `user`(`id`)
);

CREATE TABLE `admin` (
	`id`	INT	NOT NULL	AUTO_INCREMENT,
	`user_id`	INT	NOT NULL,
	`admin_status`	BOOLEAN	NOT NULL	DEFAULT FALSE,
	`expiration_date`	DATE	NULL,
	`created_at`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`updated_at`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `is_valid`	BOOLEAN	NOT NULL	DEFAULT FALSE,
    PRIMARY KEY (`id`),
    FOREIGN KEY (`user_id`) REFERENCES `user`(`id`)
);

CREATE TABLE `notice` (
	`id`	INT	NOT NULL	AUTO_INCREMENT,
	`admin_id`	INT	NOT NULL,
	`user_id`	INT	NULL,
	`title`	VARCHAR(255)	NOT NULL,
	`notice_content`	TEXT	NOT NULL,
	`created_at`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`updated_at`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`is_valid`	BOOLEAN	NOT NULL	DEFAULT TRUE,
    PRIMARY KEY (`id`),
    FOREIGN KEY (`admin_id`) REFERENCES `admin`(`id`)
);

CREATE TABLE `book_category` (
	`id`	INT	NOT NULL	AUTO_INCREMENT,
	`code`	VARCHAR(5)	NOT NULL,
	`name`	VARCHAR(50)	NOT NULL,
	`created_at`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`updated_at`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`is_valid`	BOOLEAN	NOT NULL	DEFAULT TRUE,
    PRIMARY KEY (`id`)
);

CREATE TABLE `book_info` (
	`id`	INT	NOT NULL	AUTO_INCREMENT,
	`title`	VARCHAR(255)	NOT NULL,
	`subtitle`	VARCHAR(255)	NULL,
	`author`	VARCHAR(100)	NOT NULL,
	`publisher`	VARCHAR(45)	NOT NULL,
	`publication_year`	YEAR	NOT NULL,
	`image_url`	VARCHAR(255)	NULL,
	`category_id`	INT	NOT NULL,
	`version`	VARCHAR(45)	NULL,
	`major`	BOOLEAN	NULL	DEFAULT FALSE,
	`language`	VARCHAR(10)	NOT NULL	DEFAULT '한국어',
	`created_at`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`updated_at`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`is_valid`	BOOLEAN	NOT NULL	DEFAULT TRUE,
    PRIMARY KEY (`id`),
    FOREIGN KEY (`category_id`) REFERENCES `book_category`(`id`)
);

CREATE TABLE `book_stat` (
	`id`	INT	NOT NULL	AUTO_INCREMENT,
	`book_info_id`	INT	NOT NULL,
	`review_count`	INT	NOT NULL	DEFAULT 0,
	`loan_count`	INT	NOT NULL	DEFAULT 0,
    PRIMARY KEY (`id`),
    FOREIGN KEY (`book_info_id`) REFERENCES `book_info`(`id`)
);

CREATE TABLE `book_review` (
	`id`	INT	NOT NULL	AUTO_INCREMENT,
	`user_id`	INT	NOT NULL,
	`book_info_id`	INT	NOT NULL,
	`review_content`    TEXT	NOT NULL,
	`created_at`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`updated_at`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`is_valid`	BOOLEAN	NOT NULL	DEFAULT TRUE,
    PRIMARY KEY (`id`),
    FOREIGN KEY (`user_id`) REFERENCES `user`(`id`),
    FOREIGN KEY (`book_info_id`) REFERENCES `book_info`(`id`)
);

CREATE TABLE `book` (
	`id`	INT	NOT NULL	AUTO_INCREMENT,
	`book_info_id`	INT	NOT NULL,
	`book_status`	BOOLEAN	NOT NULL    DEFAULT TRUE,
	`note`	VARCHAR(255)	NULL	DEFAULT NULL,
	`donor_name`	VARCHAR(255)	NULL	DEFAULT NULL,
	`created_at`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`updated_at`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`is_valid`	BOOLEAN	NOT NULL	DEFAULT TRUE,
    PRIMARY KEY (`id`),
    FOREIGN KEY (`book_info_id`) REFERENCES `book_info`(`id`)
);

CREATE TABLE `reservation` (
	`id`	INT	NOT NULL	AUTO_INCREMENT,
	`book_id`	INT	NOT NULL,
	`user_id`	INT	NOT NULL,
	`reservation_date`	DATE	NOT NULL,
	`reservation_status`	TINYINT	NOT NULL	DEFAULT 0,
	`created_at`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`updated_at`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`is_valid`	BOOLEAN	NOT NULL	DEFAULT TRUE,
    PRIMARY KEY (`id`),
    FOREIGN KEY (`book_id`) REFERENCES `book`(`id`),
    FOREIGN KEY (`user_id`) REFERENCES `user`(`id`)
);

CREATE TABLE `loan` (
	`id`	INT	NOT NULL	AUTO_INCREMENT,
	`book_id`	INT	NOT NULL,
	`user_id`	INT	NOT NULL,
	`loan_date`	DATE	NOT NULL,
	`due_date`	DATE	NOT NULL,
	`extend_status`	BOOLEAN	NOT NULL	DEFAULT FALSE,
	`return_status`	BOOLEAN	NOT NULL	DEFAULT FALSE,
	`return_date`	DATE    NULL,
	`overdue_days`	INT	NOT NULL	DEFAULT 0,
	`created_at`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`updated_at`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`is_valid`	BOOLEAN	NOT NULL	DEFAULT TRUE,
    PRIMARY KEY (`id`),
    FOREIGN KEY (`book_id`) REFERENCES `book`(`id`),
    FOREIGN KEY (`user_id`) REFERENCES `user`(`id`)
);

CREATE TABLE `library_setting` (
	`id`	INT	NOT NULL	AUTO_INCREMENT,
	`name`	VARCHAR(50)	NOT NULL,
	`value`	VARCHAR(50)	NOT NULL,
	`data_type`	VARCHAR(50)	NOT NULL,
	`description`	TEXT	NULL,
	`created_at`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`updated_at`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`is_valid`	BOOLEAN	NOT NULL	DEFAULT TRUE,
    PRIMARY KEY (`id`)
);
